name: kicad
base: core18
version: 5.1.0
icon: kicad.svg
summary: Electronic schematic and PCB design software
description: |
  KiCad is a suite of programs for the creation of printed circuit boards.
  It includes a schematic editor, a PCB layout tool, support tools and a
  3D viewer to display a finished & fully populated PCB.
  
  KiCad is made up of 5 main components
    * kicad - project manager
    * eeschema - schematic editor
    * pcbnew - PCB editor
    * gerbview - GERBER viewer
    * cvpcb - footprint selector for components
  
  Libraries
    * Both eeschema and pcbnew have library managers and editors for their
      components and footprints
    * You can easily create, edit, delete and exchange library items
    * Documentation files can be associated with components, footprints and key
      words, allowing a fast search by function
    * Very large libraries are available for schematic components and footprints
    * Most components have corresponding 3D models

confinement: strict
grade: stable

layout:
  /lib/kicad/plugins/3d:
    bind: $SNAP/lib/kicad/plugins/3d

plugs:
  gnome-3-28-1804: # will be replaced by gnome extension
    interface: content
    target: gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804
  gtk-3-themes: # will be replaced by gnome extension
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes: # will be replaced by gnome extension
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes: # will be replaced by gnome extension
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
  packages3d:
    interface: content
    target: $SNAP/share/kicad/modules/packages3d

apps:
  kicad:
    command: desktop-launch $SNAP/bin/kicad
    plugs: &plugs [opengl, x11, unity7, wayland, desktop, home, removable-media, network, gsettings]
    desktop: share/applications/kicad.desktop
    environment: &env {KICAD_SYMBOL_DIR: $SNAP/share/kicad/library, KISYSMOD: $SNAP/share/kicad/modules, KISYS3DMOD: $SNAP/share/kicad/modules/packages3d, KICAD_TEMPLATE_DIR: $SNAP/share/kicad/template}
  bitmap2component:
    command: desktop-launch $SNAP/bin/bitmap2component
    plugs: *plugs
    desktop: share/applications/bitmap2component.desktop
    environment: *env
  eeschema:
    command: desktop-launch $SNAP/bin/eeschema
    plugs: *plugs
    desktop: share/applications/eeschema.desktop
    environment: *env
  gerbview:
    command: desktop-launch $SNAP/bin/gerbview
    plugs: *plugs
    desktop: share/applications/gerbview.desktop
    environment: *env
  pcb-calculator:
    command: desktop-launch $SNAP/bin/pcb_calculator
    plugs: *plugs
    desktop: share/applications/pcbcalculator.desktop
    environment: *env
  pcbnew:
    command: desktop-launch $SNAP/bin/pcbnew
    plugs: *plugs
    desktop: share/applications/pcbnew.desktop
    environment: *env
  pl-editor:
    command: desktop-launch $SNAP/bin/pl_editor
    plugs: *plugs
    environment: *env

parts:
  kicad-symbols:
    plugin: dump
    source: https://github.com/KiCad/kicad-symbols.git
    source-tag: 5.1.0
    organize:
      '*.{lib,dcm}' : share/kicad/library/
      'sym-lib-table' : share/kicad/template/sym-lib-table
    stage:
      - share/kicad/

  kicad-footprints:
    plugin: dump
    source:  https://github.com/KiCad/kicad-footprints.git
    source-tag: 5.1.0
    organize:
      '*.pretty' : share/kicad/modules/
      'fp-lib-table' : share/kicad/template/fp-lib-table
    stage:
      - share/kicad/

  desktop-gtk3: # will be replaced by gnome extension
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all
    - xdg-user-dirs
    - ibus-gtk3
    - libibus-1.0-5
    - fcitx-frontend-gtk3

  ngspice:
    plugin: autotools
    source:  https://git.code.sf.net/p/ngspice/ngspice
    source-type: git
    source-tag: ngspice-30
    configflags:
      - --with-x
      - --with-readline=yes
      - --disable-debug
      - --with-ngshared
      - --enable-xspice
      - --enable-cider
    build-packages:
      - libreadline-dev
      - bison
      - flex
  
  kicad-i18n:
    plugin: cmake
    source: https://github.com/KiCad/kicad-i18n.git
    source-type: git
    source-tag: 5.1.0
    configflags:
      - -GNinja
    build-packages:
      - ninja-build
      - gettext
  
  kicad:
    after: [ngspice, desktop-gtk3]
    plugin: cmake
    source: https://github.com/KiCad/kicad-source-mirror.git
    source-type: git
    source-tag: 5.1.0
    build-environment:
      - LIBRARY_PATH: $SNAPCRAFT_STAGE/lib
    override-stage: |
      snapcraftctl stage
      # patch desktop files with correct icon paths
      SED_CMD="sed -i -E s|^Icon=(.*)|Icon=\${SNAP}/share/icons/hicolor/scalable/apps/\1.svg|g"
      for file in share/applications/*.desktop
      do
        $SED_CMD "$file"
      done
    configflags:
      - -GNinja
      - -DCMAKE_BUILD_TYPE=Release
      - -DKICAD_SPICE=ON
      - -DNGSPICE_INCLUDE_PATH=$SNAPCRAFT_STAGE/include/
      - -DNGSPICE_LIBRARY_PATH=$SNAPCRAFT_STAGE/lib/
      - -DKICAD_SCRIPTING=ON
      - -DKICAD_SCRIPTING_MODULES=ON
      - -DKICAD_SCRIPTING_WXPYTHON=ON
      - -DKICAD_SCRIPTING_PYTHON3=ON
      - -DKICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
      - -DPYTHON_EXECUTABLE=/usr/bin/python3
      - -DKICAD_USER_CONFIG_DIR=$SNAP_USER_COMMON
    
    stage-packages:
      - libgl1
      - libglew2.0
      - libglu1-mesa
      - libglx0
      - libglvnd0
      - libilmbase12
      - libice6
      - libopenexr22
      - libsm6
      - liboce-modeling11
      - liboce-ocaf11
      - liboce-ocaf-lite11
      - liboce-foundation11
      - liboce-visualization11
      - libx11-6
      - libxau6
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxxf86vm1
      - libasn1-8-heimdal
      - libatk1.0-0
      - libcairo2
      - libcurl4
      - libdatrie1
      - libfontconfig1
      - libfreeimage3
      - libfreetype6
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libgomp1
      - libgraphite2-3
      - libgssapi3-heimdal
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libjbig0
      - libjpeg-turbo8
      - libjxr0
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - liblcms2-2
      - libnghttp2-14
      - libnotify4
      - libopenjp2-7
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpsl5
      - libraw16
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libthai0
      - libtiff5
      - libwebp6
      - libwebpmux3
      - libwind0-heimdal
      - libwxbase3.0-0v5
      - libwxgtk3.0-gtk3-0v5
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libpython3.6

    build-packages:
      - sed
      - ninja-build
      - g++
      - libwxbase3.0-dev
      - libwxgtk3.0-gtk3-dev
      - libglew-dev
      - libglm-dev
      - libcurl4-openssl-dev
      - libcairo2-dev
      - libboost-context-dev 
      - libboost-dev 
      - libboost-system-dev 
      - libboost-test-dev
      - liboce-foundation-dev
      - liboce-ocaf-dev
      - python3
      - python3-dev
      - python3-wxgtk4.0
      - libgl1-mesa-dev
      - libssl-dev
      - swig3.0
      - libboost-filesystem-dev