name: kicad5-packages3d
base: core18
version: 5.1.2
summary: Official KiCad 3D model libraries for rendering and MCAD integration
description: |
  This package contains 3D models for KiCad 5. 
  These 3D models are best used in combination with the official footprint libs.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: all
    
parts:
  kicad-packages3d:
    plugin: dump
    source: https://github.com/KiCad/kicad-packages3D.git
    source-tag: 5.1.2

slots:
  packages3d:
    interface: content
    content: packages3d
    read: [$SNAP]
